youshido-php/GraphQL

README.md
Hey - This is to correct the example 
AbstractInputObjectType is on the InputObject folder.
=> Fix: Incorrect AbstractInputObjectType location

examples/03_relay_star_wars/Schema/FactionType.php
Changed `GraphQl` to `GraphQL`.
Typo prevented class ArrayConnection to be found.
=> Fixed typo in example

Tests/DataProvider/TestObjectType.php, Tests/DataProvider/TestSchema.php, Tests/Schema/ProcessorTest.php, src/Execution/Processor.php, src/Introspection/FieldType.php
fix for https://github.com/Youshido/GraphQL/issues/12.  Without this, nested queries that have both resolveFuncs and arguments complain:
```
{errors: {message: "Value is not set for variable \"value\""}}
```
I'm not sure this is the cleanest fix, I defer to the authors on that.
=> validate query arguments while processing AST

Tests/Library/Utilities/TypeUtilitiesTest.php, src/Type/TypeService.php
Currently objects only support `$foo->getBar()` getters by default, this enables `$foo->bar` as well.  Provides symmetry with arrays which support `$foo['bar']`.
=> allow default typeservice to resolve public fields on objects

src/Execution/Processor.php, src/Validator/ResolveValidator/ResolveValidator.php
phpstorm autocompletion oopsie 😄 
If you can, please remove this check entirely; we have classes that implement `__sleep` instead of `\Serializable`, so this check doesn't work there.
In general determining if an object is serializable is a Hard problem since `[function() {}]` is not serializable, so I don't think this check is very useful.
=> remove mongo dependency

src/Introspection/QueryType.php
Our introspection result contains currently invalid data in possibleTypes in the introspection:
```json
{
"possibleTypes": [
{
"kind": "OBJECT",
"name": "Author",
"ofType": null
},
{
"kind": "OBJECT",
"name": "Author",
"ofType": null
},
{
"kind": "OBJECT",
"name": "Project",
"ofType": null
},
]
}
```
We have two interfaces and both show the same possibleTypes, althought this is not true.
* `Project` and `Author` implement `NodeInterface`
* `Author` also implements `PersonInterface`
These happens because in `resolvePossibleTypes()` currently the check assumes that every interface has a different class. But we do not use the OOP way of defining Types (we use annotations and compile them to arrays). So the class is always `Youshido\GraphQL\Type\InterfaceTypeInterfaceType`.
Changing the check …
=> Fix invalid content in introspection possibleTypes

Tests/Library/Validator/ResolveValidatorTest.php, Tests/Parser/RequestTest.php, Tests/Parser/VariableTest.php, src/Execution/Request.php, src/Parser/Ast/ArgumentValue/Variable.php, src/Validator/ResolveValidator/ResolveValidator.php
Considering following query 
```javascript
query ($limit: Int!, $offset: Int!) {
postList(__limit: $limit, __offset: $offset) {
title
slug
}
}
```
And following variables
```json
{"limit": 1, "offset": 0}
```
There are multiples bad type check which cause issues with integer values as PHP evaluate directly integer values as boolean ... We need to strict test `null` values !
Also add an array cast for json values in `Request::setVariables()`. Dunno if it's the right fix for this last one.
=> Integer variables causes many crash

src/Config/Traits/FieldsAwareConfigTrait.php, src/Config/Traits/ResolvableObjectTrait.php, src/Execution/Processor.php, src/Execution/ResolveInfo.php, src/Field/AbstractField.php, src/Field/AbstractInputField.php, src/Field/FieldInterface.php, src/Introspection/FieldType.php, src/Type/Traits/AutoNameTrait.php, src/Validator/ConfigValidator/Rules/TypeValidationRule.php, src/Validator/ResolveValidator/ResolveValidator.php, src/Validator/ResolveValidator/ResolveValidatorInterface.php
Removed usages of AbstractField (except extends) in favour of FieldInterface to loose coupling between Processor and Field implementations. 
Extended FieldInterface with necessary methods.
=> Use FieldInterface instead of AbstractField 

Tests/Library/Field/InputFieldTest.php, Tests/Schema/IntrospectionTest.php, src/Introspection/InputValueType.php
The spec clearly says that the defaultValue is a string representation of the value. 
http://facebook.github.io/graphql/#sec-The-__InputValue-Type
Currently this library puts the plain value (int, bool, string) as defaultValue.
By looking at other implementations this is how values are converted:
```
1 => '1'
'1' => '"1"'
null => null
false => 'false'
```
I'm not sure if the place where I fixed it is correct, but the test should be correct.
Without this fix relay and graphql-js both choke on the exported introspection schema.
=> use json_encode to resolve defaultValue for args

Tests/Library/Type/InputObjectTypeTest.php
I'm having trouble with setting an InputObject to null if it has a field that is not nullable.
In the test author is an inputobject with a nonnullable field name, but author itself is nullable.
It however gives an error.
=> add test for a Nullable InputObject with a NonNullable field

src/Type/Scalar/DateTimeType.php
Currently its misleading to the api user on what datetime format is expected when its different from the default
=> Have the DateTimeType description be dynamic to the format used

Tests/Parser/VariableTest.php, src/Execution/Request.php, src/Parser/Ast/ArgumentValue/Variable.php, src/Parser/Parser.php, src/Parser/Token.php, src/Parser/Tokenizer.php
Simple variable default values, as discussed in #144 & #148 
Changes are backwards compatible, tested it with some types. Would be great to hear feedback from others if this works for them or if I'm missing something :)
=> Variable default values

README.md
I've noticed that the links to examples weren't working, while studying the readme.md. This PR fixes the links.
=> Fix GitHub links for examples

README.md
Hey there! I'm making this PR with the best of intentions, but I'm sure it'll be taken as aggressive. Not the goal. 
Recently I've been [trying to explain to people](https://philsturgeon.uk/api/2017/01/24/graphql-vs-rest-overview/) the differences between GraphQL and REST and debunk some of the "GraphQL is magically better" stuff going around. Your introduction is furthering the issue. 
Generally, GraphQL and REST are just different, and pretending that one is better is going to confuse people.
> self-checks embedded on the ground level of your backend architecture
What does this mean
> reusable API for different client versions and devices, i.e. no more need in maintaining "/v1" and "/v2"
This was never recommended in REST, in fact the opposite was recommended. [Evolvability is king for …
=> More realistic GraphQL vs REST explanation

src/Type/Scalar/BooleanType.php
By default `BooleanType` has the name of 'Boolean', that works for most cases. But in the edge cases it's better to explicitly return the name of 'Boolean', and keep consistent with other scalar types like 'StringType', 'IntType'.
For example some dependent library will override it:
```php
class GraphQLBoolean extends BooleanType {
}
```
The `GraphQLBoolean` type ends up getting an odd name of 'GraphQLBoo'
=> Explicitly return Boolean type name

Tests/Library/Type/InputObjectTypeTest.php, Tests/Schema/NonNullableTest.php, Tests/Schema/ProcessorTest.php, Tests/Schema/VariablesTest.php, src/Type/Enum/AbstractEnumType.php, src/Type/InputObject/AbstractInputObjectType.php, src/Type/ListType/AbstractListType.php, src/Type/NonNullType.php, src/Validator/ResolveValidator/ResolveValidator.php
When objects are validated, they just check if their contained field values are valid, but are not able attach instructions to the validation result. This PR intensifies the usage of the 'last error' feature to introduce a limited form of error message bubbling. By appending nested errors, we get some more useful information about the location of the invalid data as well. You can see this in action in some of the tests, where the 'nested' error messages are separated by colons in the resulting error message. Before this, the library would tell you your input object would be invalid. Now it tells you that's because property X is NULL and mustn't be, greatly reducing debugging time.
I couldn't find any information on code style in the project README or in the Travis CI configuration. Please …
=> Improve validation error message bubbling.

Tests/DataProvider/TestScalarDataProvider.php
One of the test fixtures was a little unstable already, because it would compare individually instantiated times and assume they'd be identical (which would fail if the test was run exactly when the clock changed). PHP 7.1 also introduced a [backwards-incompatible change](http://php.net/manual/en/migration71.incompatible.php#migration71.incompatible.datetime-microseconds) to `\DateTime('now')`, which these same fixtures uses, exacerbating the problem. This PR fixes both issues.
=> Fix code that would run into arbitrary date comparison failures, partly caused by backwards-incompatible changes in PHP 7.1.

src/Execution/Container/Container.php
Small fix, causing an exception to be thrown that sprintf has too few arguments.
=> Add missing variable for sprintf

src/Execution/Processor.php
When an exception is thrown during deferred resolving, the result still has to be unpacked or we end up with deferred resolvers in the result.
=> Properly handling errors during deferred resolving.

Tests/Library/Type/ScalarTypeTest.php, src/Type/Scalar/DateTimeType.php, src/Type/Scalar/DateTimeTzType.php
The `DateTimeType` and `DateTimeTzType` currently map to the `\DateTime` PHP object.
Yet, using the `DateTimeImmutable` object (introduced in PHP 5.5) is a best practice to avoid side effects.
This PR introduces support for the `DateTimeImmutable` while keeping BC compatibility.
With this PR, a `DateTimeType` or `DateTimeTzType` can accept a `DateTimeImmutable` instance as well as a `DateTime` instance. Serialization keeps returning a `DateTime` object for compatibility reasons. It might be interesting to switch to `DateTimeImmutable` on the next major release.
=> DateTimeXxType now accepts DateTimeImmutable inputs

Tests/Parser/ParserTest.php, src/Parser/Tokenizer.php
This is for https://github.com/Youshido/GraphQL/issues/195 - assuming that there's agreement that #195 is in fact a bug, then here's a proposed fix.
String values parsed from queries and mutations were not being unescaped per http://facebook.github.io/graphql/October2016/#sec-String-Value
This code updates Tokenizer.php:scanString() to returned the un-escaped version of the string.
Issues to consider in the PR:
- I think: For when variable values are passed in to the initial query / mutation via the top level 'variables' array, then those don't go through this path, instead have been unescaped by json_decode() directly, and thus are not graphQL string values.
- As written, Tokenizer.php:scanString() has issues even if it's intended to return an escaped/raw version of the string / raw …
=> Un-escaping of string values

Tests/Library/Type/SchemaDirectivesListTest.php, Tests/Schema/IntrospectionTest.php, src/Directive/DirectiveLocation.php, src/Introspection/DirectiveLocationType.php
FIELD_DEFINITION and ENUM_VALUE are valid directive locations, for example with @deprecated. This adds them to the list, and provides some test cases around directives in introspection queries.
=> Added missing directive locations

src/Execution/Processor.php
https://github.com/Youshido/GraphQL/commit/8a01f948183e5d93f030e50e4016713e13cdb0e2#diff-6ba3444ce11b8aef21a5cd104bf1e5e4R357
The line change (linked above) caused a regression when resolving fragments.
=> Fixing regression from PR for Issue #151

.gitignore, src/Execution/Context/ExecutionContext.php, src/Execution/Processor.php, src/Validator/ResolveValidator/ResolveValidator.php
In a project I'm working on we're caching the `Processor` instance to speed up the bootstrapping time of each GraphQL request. Since the `Processor` has the `Schema` as a member this alone speeds up execution time somewhat since the schema doesn't have to parsed on every request.
During further investigation I noticed that a lot of processing time is spent on resolving things. Specifically, each time an object is resolved, the `Type` has to be built and its `Field`s need to be parsed and validated. This process is not slow per se, but `getFields()` (which calls `getConfig()`, which calls `build()`) ends up being called a lot, which increases execution time in the long run.
Since `Type`s and `Field`s don't magically change between requests (and even between deployments), I figured we can …
=> Add a type/field lookup cache for improved performance

src/Execution/Processor.php
This tiny code change allows deferred resolvers to return another deferred resolver.
=> Nested deferred resolvers

.travis.yml
From https://travis-ci.community/t/php-5-4-and-5-5-archives-missing/3723/5
=> Attempt to fix Travis CI builds on PHP 5.5

examples/01_sandbox/index.php, examples/02_blog/Schema/PostType.php, examples/02_blog/index.php, examples/02_blog/schema-bootstrap.php, examples/02_blog_inline/index.php, examples/02_blog_inline/inline-schema.php
* If no autoload found in parent, use local autoload
* Example 2, explode() expects parameter 2 to be string, array given, fixed
* Example 2, Unknown argument "truncated" on field "title", fixed
=>  Run examples, small corrections

Tests/Library/Relay/NodeTest.php, src/Relay/Node.php
This pull request is to make Node::fromGlobalId() not break when the input id is not in the format that was expected.
This now throws an `InvalidArgumentException` if the input is invalid instead of `[null, null]` as the calling code would be unlikely to recover from it, but happy to change this back if desired.
=> Change Node::fromGlobalId() to be stricter about validating input

Tests/Issues/Issue210/TypeServiceTest.php, Tests/Issues/Issue98/TypeServiceTest.php, Tests/Library/Type/UnionTypeTest.php, Tests/Library/Utilities/TypeUtilitiesTest.php, composer.json, src/Type/TypeService.php
Fixes #210, also incidentally fixes #203, closes #98 
I added some test cases against the initial implementation first, then some broken test cases, then switched to using `symfony/property-accessor` and all the tests started passing. A net gain in my opinion.
A third parameter `$enableMagicCall` has been added to `getPropertyValue()` to allow resolving properties from objects implementing `__call()` for getters. It's an optional feature of `symfony/property-accessor` and can be quite obscure if implicitly enabled, so I added a flag for it.
=> Add more robust implementation for TypeService::getPropertyValue()
